spring:
  application:
    name: qq-read-task
qqread:
  push-key: 'SCU138193T2b2331d7d6b3da86610a44e6a49a4de65fe2bf9c86265'
  cron:
    daily-task: 0 0 8 * * ? # 每天上午8点运行一次
    add-read-time: 0 4/10 * * * ? # 每10分钟运行一次
    open-box: 0 0/2 * * * ?  # 每2分钟运行一次
    cycle-task: 0 0 8-20 * * ? # 每天8~20点运行，每小时运行一次
    withdraw: 0 0 0 * * ? # 每天凌晨0点运行一次
    notify: 0 0 23 * * ? # 每天23点运行一次
  configs:
    - qq: 1398371419
      ywsession: btges9uft294gal7uljxtxvb34ub8qjq
      cookie: 'ywguid=1398371419;ywkey=ywCD5k6WhEQi;platform=android;channel=mqqmina;mpVersion=0.33.3;qq_ver=8.3.9.2952;os_ver=Android 10;mpos_ver=1.16.0;platform=android;openid=BE8F85D640E85BB13C942C8DE01B0363'
      bookUrl: https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=2014&refer=-1&bid=27325720&readTime=5523&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%229%22%3A%7B%22readTime%22%3A5523%2C%22pay_status%22%3A0%7D%7D%5D&sp=-1
      maxDailyReadTime: 631
      openid: BE8F85D640E85BB13C942C8DE01B0363
      guid: 1398371419
      session: btges9uft294gal7uljxtxvb34ub8qjq
      scene: 2014
      source: -1
